from typing import NewType

__all__ = [
    "GLFWWindow",
    "enter_glfw_window",
    "exit_glfw_window",
    "enter_imgui_window",
    "exit_imgui_window",
    "glfw_window_should_close",
    "glfw_poll_events",
    "enter_frame",
    "exit_frame",
    "enter_window",
    "exit_window",
    "show_text",
    "show_float_slider",
]

GLFWWindow = NewType("GLFWWindow", object)

def enter_glfw_window(title: str) -> GLFWWindow: ...
def exit_glfw_window(window: GLFWWindow) -> None: ...
def enter_imgui_window(window: GLFWWindow) -> None: ...
def exit_imgui_window(window: GLFWWindow) -> None: ...
def glfw_window_should_close(window: GLFWWindow) -> bool: ...
def glfw_poll_events() -> None: ...
def enter_frame() -> None: ...
def exit_frame(window: GLFWWindow) -> None: ...
def enter_window(title: str) -> None: ...
def exit_window() -> None: ...
def show_text(text: str) -> None: ...
def show_float_slider(floatv) -> None: ...
